Repository ZerataX/yacx, pull requests merged in 2020-04, with the labels that each got.

#148 KernelTime refactor
  include/yacx/Devices.hpp
  include/yacx/KernelArgs.hpp
  include/yacx/KernelTime.hpp
  src/Kernel.cpp
  src/KernelArgs.cpp
  src/KernelTime.cpp
  src/jni/KernelUtils.cpp
  src/main/java/yacx/Executor.java
  src/main/java/yacx/KernelTime.java
Labels: enhancement

#113 Source tests
  test/test_source.cpp
Labels: help wanted, tests

#114 Kernel tests
  test/test_kernel.cpp
  test/test_program.cpp
Labels: help wanted, tests

#165 add nix-shell
  CMakeLists.txt
  examples/CMakeLists.txt
  shell.nix
  test/CMakeLists.txt
  yacx.sh
Labels: bug, enhancement

#162 bash autocompletions
  yacx-completion.bash
  yacx.sh
Labels: enhancement

#163 [WIP] document usage better
  .github/workflows/docs.yml
  Doxyfile
  README.MD
  examples/makefile
  makefile
  shell.nix
  test/makefile
Labels: documentation

#164 Fertigstellung_Example
  examples/CMakeLists.txt
  examples/example_matrix_multiply.cpp
  examples/example_program.cpp
  examples/example_saxpy.cpp
  examples/example_sumArray.cpp
  examples/kernels/sum_Array.cu
  src/KernelTime.cpp
Labels: help wanted
